server:
  port: 18086
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  zipkin:
    discovery-client-enabled: false
    base-url: http://localhost:9411
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  elasticsearch:
    rest:
      uris: http://192.168.37.132:9200
  jackson:
    default-property-inclusion: non_null
  thymeleaf: #关闭缓存
    cache: false
  rabbitmq:
    virtual-host: /mrding
    host: 192.168.37.132
    port: 5672
    username: mrding
    password: mrding
    listener:
      simple:
        acknowledge-mode: manual #手动提交
        prefetch: 1 #能者多劳
        concurrency: 3 #多线程
feign:
  sentinel:
    enabled: true

