server:
  port: 18089
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  zipkin:
    base-url: http://localhost:9411/
    sender:
      type: web
    discovery-client-enabled: false
  sleuth:
    sampler:
      probability: 1
  redis:
    host: 192.168.37.132
  thymeleaf:
    cache: false
feign:
  sentinel:
    enabled: true
auth:
  jwt:
    pubKeyPath: D:\\ideaIU-2019.2\\workspace-gulishop\\rsa\\rsa.pub
    priKeyPath: D:\\ideaIU-2019.2\\workspace-gulishop\\rsa\\rsa.pri
    secret: 123/*-+!@#$%^&*()asdfjkl;ASDFJLK?.
    cookieName: GMALL_TOKEN
    expire: 180
    unick: unick