server:
  port: 18081
feign:
  sentinel:
    enabled: true
mybatis-plus:
  mapper-locations: classpath:mapper/pms/**/*.xml
  type-aliases-package: com.atguigu.gmall.pms.entity
  global-config:
    db-config:
      id-type: auto
spring:
  cloud:
    alibaba:
      seata:
        tx-service-group: pms-service-fescar-service-group
  rabbitmq:
    virtual-host: /mrding
    host: 192.168.37.132
    port: 5672
    username: mrding
    password: mrding
    publisher-confirm-type: correlated #异步方式提交
    publisher-returns: true

