server:
  port: 18083
mybatis-plus:
  mapper-locations: classpath:mapper/wms/*.xml
  type-aliases-package: com.atguigu.gmall.wms.entity
  global-config:
    db-config:
      id-type: auto
feign:
  sentinel:
    enabled: true